version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "softprops/action-gh-release"
        versions:
          - "2.2.0"
  - package-ecosystem: "npm"
    directory: "webui"
    schedule:
      interval: "weekly"
    groups:
      angular:
        patterns:
          - "@angular*"
        update-types:
          - "minor"
          - "patch"
