name: Build Engine

on:
  pull_request:
    paths:
      - 'engines/**'

jobs:
  findengine:
    runs-on: ubuntu-latest
    outputs:
      engine: ${{ steps.findname.outputs.engine }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Find Engine Name
      id: findname
      uses: luxtorpeda-dev/action-build-get-engine-name@v3
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    needs: findengine
    container:
      image: luxtorpedadev/runtime:7
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: ./common/start_build.sh ${{needs.findengine.outputs.engine}}
    - name: Package
      run: ./common/package.sh ${{needs.findengine.outputs.engine}}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist
